//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("Adventure.Domain", "ForeignKeyConstraint1", "GameObject", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Adventure.Data.GameObject), "GameObject1", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Adventure.Data.GameObject), true)]
[assembly: EdmRelationshipAttribute("Adventure.Domain", "ForeignKeyExitToAlias", "GameObject", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Adventure.Data.GameObject), "ExitAlias", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Adventure.Data.ExitAlias), true)]
[assembly: EdmRelationshipAttribute("Adventure.Domain", "ForeignKeyDestinationToObject", "GameObject", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Adventure.Data.GameObject), "GameObject1", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Adventure.Data.GameObject), true)]

#endregion

namespace Adventure.Data
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class AdventureDBEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new AdventureDBEntities object using the connection string found in the 'AdventureDBEntities' section of the application configuration file.
        /// </summary>
        public AdventureDBEntities() : base("name=AdventureDBEntities", "AdventureDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new AdventureDBEntities object.
        /// </summary>
        public AdventureDBEntities(string connectionString) : base(connectionString, "AdventureDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new AdventureDBEntities object.
        /// </summary>
        public AdventureDBEntities(EntityConnection connection) : base(connection, "AdventureDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<C__RefactorLog> C__RefactorLog
        {
            get
            {
                if ((_C__RefactorLog == null))
                {
                    _C__RefactorLog = base.CreateObjectSet<C__RefactorLog>("C__RefactorLog");
                }
                return _C__RefactorLog;
            }
        }
        private ObjectSet<C__RefactorLog> _C__RefactorLog;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<GameObject> GameObjects
        {
            get
            {
                if ((_GameObjects == null))
                {
                    _GameObjects = base.CreateObjectSet<GameObject>("GameObjects");
                }
                return _GameObjects;
            }
        }
        private ObjectSet<GameObject> _GameObjects;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ExitAlias> ExitAliases
        {
            get
            {
                if ((_ExitAliases == null))
                {
                    _ExitAliases = base.CreateObjectSet<ExitAlias>("ExitAliases");
                }
                return _ExitAliases;
            }
        }
        private ObjectSet<ExitAlias> _ExitAliases;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the C__RefactorLog EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToC__RefactorLog(C__RefactorLog c__RefactorLog)
        {
            base.AddObject("C__RefactorLog", c__RefactorLog);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the GameObjects EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToGameObjects(GameObject gameObject)
        {
            base.AddObject("GameObjects", gameObject);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ExitAliases EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToExitAliases(ExitAlias exitAlias)
        {
            base.AddObject("ExitAliases", exitAlias);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Adventure.Domain", Name="C__RefactorLog")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class C__RefactorLog : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new C__RefactorLog object.
        /// </summary>
        /// <param name="operationKey">Initial value of the OperationKey property.</param>
        public static C__RefactorLog CreateC__RefactorLog(global::System.Guid operationKey)
        {
            C__RefactorLog c__RefactorLog = new C__RefactorLog();
            c__RefactorLog.OperationKey = operationKey;
            return c__RefactorLog;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid OperationKey
        {
            get
            {
                return _OperationKey;
            }
            set
            {
                if (_OperationKey != value)
                {
                    OnOperationKeyChanging(value);
                    ReportPropertyChanging("OperationKey");
                    _OperationKey = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("OperationKey");
                    OnOperationKeyChanged();
                }
            }
        }
        private global::System.Guid _OperationKey;
        partial void OnOperationKeyChanging(global::System.Guid value);
        partial void OnOperationKeyChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Adventure.Domain", Name="ExitAlias")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ExitAlias : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ExitAlias object.
        /// </summary>
        /// <param name="aliasId">Initial value of the AliasId property.</param>
        /// <param name="exitId">Initial value of the ExitId property.</param>
        /// <param name="alais">Initial value of the Alais property.</param>
        public static ExitAlias CreateExitAlias(global::System.Int32 aliasId, global::System.Int32 exitId, global::System.String alais)
        {
            ExitAlias exitAlias = new ExitAlias();
            exitAlias.AliasId = aliasId;
            exitAlias.ExitId = exitId;
            exitAlias.Alais = alais;
            return exitAlias;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AliasId
        {
            get
            {
                return _AliasId;
            }
            set
            {
                if (_AliasId != value)
                {
                    OnAliasIdChanging(value);
                    ReportPropertyChanging("AliasId");
                    _AliasId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("AliasId");
                    OnAliasIdChanged();
                }
            }
        }
        private global::System.Int32 _AliasId;
        partial void OnAliasIdChanging(global::System.Int32 value);
        partial void OnAliasIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ExitId
        {
            get
            {
                return _ExitId;
            }
            set
            {
                OnExitIdChanging(value);
                ReportPropertyChanging("ExitId");
                _ExitId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ExitId");
                OnExitIdChanged();
            }
        }
        private global::System.Int32 _ExitId;
        partial void OnExitIdChanging(global::System.Int32 value);
        partial void OnExitIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Alais
        {
            get
            {
                return _Alais;
            }
            set
            {
                OnAlaisChanging(value);
                ReportPropertyChanging("Alais");
                _Alais = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Alais");
                OnAlaisChanged();
            }
        }
        private global::System.String _Alais;
        partial void OnAlaisChanging(global::System.String value);
        partial void OnAlaisChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Adventure.Domain", "ForeignKeyExitToAlias", "GameObject")]
        public GameObject GameObject
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<GameObject>("Adventure.Domain.ForeignKeyExitToAlias", "GameObject").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<GameObject>("Adventure.Domain.ForeignKeyExitToAlias", "GameObject").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<GameObject> GameObjectReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<GameObject>("Adventure.Domain.ForeignKeyExitToAlias", "GameObject");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<GameObject>("Adventure.Domain.ForeignKeyExitToAlias", "GameObject", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Adventure.Domain", Name="GameObject")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class GameObject : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new GameObject object.
        /// </summary>
        /// <param name="gameObjectId">Initial value of the GameObjectId property.</param>
        public static GameObject CreateGameObject(global::System.Int32 gameObjectId)
        {
            GameObject gameObject = new GameObject();
            gameObject.GameObjectId = gameObjectId;
            return gameObject;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 GameObjectId
        {
            get
            {
                return _GameObjectId;
            }
            set
            {
                if (_GameObjectId != value)
                {
                    OnGameObjectIdChanging(value);
                    ReportPropertyChanging("GameObjectId");
                    _GameObjectId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("GameObjectId");
                    OnGameObjectIdChanged();
                }
            }
        }
        private global::System.Int32 _GameObjectId;
        partial void OnGameObjectIdChanging(global::System.Int32 value);
        partial void OnGameObjectIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name = "";
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description = "";
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Location_Id
        {
            get
            {
                return _Location_Id;
            }
            set
            {
                OnLocation_IdChanging(value);
                ReportPropertyChanging("Location_Id");
                _Location_Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Location_Id");
                OnLocation_IdChanged();
            }
        }
        private Nullable<global::System.Int32> _Location_Id;
        partial void OnLocation_IdChanging(Nullable<global::System.Int32> value);
        partial void OnLocation_IdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Type
        {
            get
            {
                return _Type;
            }
            set
            {
                OnTypeChanging(value);
                ReportPropertyChanging("Type");
                _Type = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Type");
                OnTypeChanged();
            }
        }
        private global::System.String _Type = "Item";
        partial void OnTypeChanging(global::System.String value);
        partial void OnTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Destination
        {
            get
            {
                return _Destination;
            }
            set
            {
                OnDestinationChanging(value);
                ReportPropertyChanging("Destination");
                _Destination = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Destination");
                OnDestinationChanged();
            }
        }
        private Nullable<global::System.Int32> _Destination;
        partial void OnDestinationChanging(Nullable<global::System.Int32> value);
        partial void OnDestinationChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Adventure.Domain", "ForeignKeyConstraint1", "GameObject1")]
        public EntityCollection<GameObject> Inventory
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<GameObject>("Adventure.Domain.ForeignKeyConstraint1", "GameObject1");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<GameObject>("Adventure.Domain.ForeignKeyConstraint1", "GameObject1", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Adventure.Domain", "ForeignKeyConstraint1", "GameObject")]
        public GameObject Location
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<GameObject>("Adventure.Domain.ForeignKeyConstraint1", "GameObject").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<GameObject>("Adventure.Domain.ForeignKeyConstraint1", "GameObject").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<GameObject> LocationReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<GameObject>("Adventure.Domain.ForeignKeyConstraint1", "GameObject");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<GameObject>("Adventure.Domain.ForeignKeyConstraint1", "GameObject", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Adventure.Domain", "ForeignKeyExitToAlias", "ExitAlias")]
        public EntityCollection<ExitAlias> ExitAliases
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ExitAlias>("Adventure.Domain.ForeignKeyExitToAlias", "ExitAlias");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ExitAlias>("Adventure.Domain.ForeignKeyExitToAlias", "ExitAlias", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Adventure.Domain", "ForeignKeyDestinationToObject", "GameObject1")]
        public EntityCollection<GameObject> InboundExits
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<GameObject>("Adventure.Domain.ForeignKeyDestinationToObject", "GameObject1");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<GameObject>("Adventure.Domain.ForeignKeyDestinationToObject", "GameObject1", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Adventure.Domain", "ForeignKeyDestinationToObject", "GameObject")]
        public GameObject DestinationLocation
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<GameObject>("Adventure.Domain.ForeignKeyDestinationToObject", "GameObject").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<GameObject>("Adventure.Domain.ForeignKeyDestinationToObject", "GameObject").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<GameObject> DestinationLocationReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<GameObject>("Adventure.Domain.ForeignKeyDestinationToObject", "GameObject");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<GameObject>("Adventure.Domain.ForeignKeyDestinationToObject", "GameObject", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
